# Generated by Django 5.2.14 on 2026-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travisjr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
